source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "erubis"
gem "minitest"
gem "rack"
gem "redcarpet"
gem "bcrypt"
gem "pry"
gem "pry-nav" 
gem 'pry-debugger'
  gem 'awesome_print'
  gem 'racksh'
  gem 'debugger'

